# Generated by Django 4.0.4 on 2022-08-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bml',
            name='image_url',
            field=models.JSONField(),
        ),
    ]
