# Generated by Django 4.1.1 on 2022-09-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bm',
            name='list_items_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
